# Generated by Django 4.1.3 on 2023-01-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0003_rename_post_rating_emprendimiento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="emprendimiento",
            new_name="emprendimientorate",
        ),
    ]
