# Generated by Django 4.1.3 on 2023-01-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0004_rename_emprendimiento_rating_emprendimientorate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="emprendimientorate",
            new_name="emprendimiento",
        ),
    ]
