# Generated by Django 4.1.3 on 2023-02-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0006_alter_emprendimiento_descripcion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprendimiento",
            name="productos",
        ),
    ]
