# Generated by Django 4.1.3 on 2023-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0007_remove_emprendimiento_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprendimiento",
            name="productos",
            field=models.ManyToManyField(
                related_name="producto",
                to="administrativo.producto",
                verbose_name="Productos",
            ),
        ),
    ]
